name: Docker Build and Push

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'apps/**'
      - '.github/workflows/docker-build.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'apps/**'

env:
  AWS_REGION: eu-west-2

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        app: [frontend, backend, api]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: eks-multi-app-${{ matrix.app }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        if [ -d "apps/${{ matrix.app }}" ]; then
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG apps/${{ matrix.app }}
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
        else
          echo "Directory apps/${{ matrix.app }} does not exist, skipping"
        fi
        
    - name: Update image tag in ArgoCD manifests
      if: github.ref == 'refs/heads/main'
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        if [ -f "k8s/apps/${{ matrix.app }}/deployment.yaml" ]; then
          sed -i "s|image: .*/${{ matrix.app }}:.*|image: ${{ steps.login-ecr.outputs.registry }}/eks-multi-app-${{ matrix.app }}:$IMAGE_TAG|" k8s/apps/${{ matrix.app }}/deployment.yaml
        fi
        
    - name: Commit and push updated manifests
      if: github.ref == 'refs/heads/main'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add k8s/apps/${{ matrix.app }}/deployment.yaml || true
        git diff --staged --quiet || git commit -m "Update ${{ matrix.app }} image to ${{ github.sha }}"
        git push || true